config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

def index
  @flats = Flat.all
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>All our Flats(<%= @flats.size %>)</h1>

  <ul>
    <% @flats.each do |flat| %>
      <div class="card-product">
        <%= image_tag flat.picture_url %>
        <div class="card-product-infos">
          <li><h2><%= flat.name %></h2></li>
          <li><p><%= flat.description %></p></li>
          <li>sleeps <%= flat.number_of_guests %></li>
          <li><%= flat.price_per_night %>$/night</li>
            <div class="flat-card-actions">
              <%= link_to 'More info', flat_path(flat) %>
              <%= link_to 'Edit', edit_flat_path(flat), class: 'ms-3 text-warning' %>
              <%= link_to "Remove", flat_path(flat),
                  method: :delete,
                  data: { confirm: "Are you sure?" },
                  class: 'ms-3 text-danger'%>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnbRemake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Bakbak+One&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Display:wght@100&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>